apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BamijiOmo/argofleet-canada.git
    targetRevision: HEAD
    path: k8s/base/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: argofleet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

